export const isProductionEnvironment = process.env.NODE_ENV === "production";

export const isTestEnvironment = Boolean(
  process.env.PLAYWRIGHT_TEST_BASE_URL ||
    process.env.PLAYWRIGHT ||
    process.env.CI_PLAYWRIGHT
);

export const SESSION_TEMPLATES = [
  {
    id: 0,
    title: "Welcome & Orientation",
    description:
      "Get started with your career journey and understand the process",
    duration: "15 min", //duration for the full session
    icon: "Rocket",
    forms: [
      {
        id: "demographics-details",
        title: "Demographics Details",
        description: "Tell us about yourself and your career aspirations",
        estimatedTime: "5 min",
        status: "completed",
        completedAt: "2024-01-10",
        score: 100,
        icon: "User",
        route: "/journey/session/0/q/demographics-details",
        topics: ["Personal Info", "Professional Info", "Coaching Experience"],
        difficulty: "beginner",
      },
    ],
    status: "completed",
    completedAt: "2024-01-10",
    score: 95,
    topics: ["Demographics Details"],
    learningObjectives: [
      "Understand the career exploration process",
      "Set initial career goals",
      "Navigate the platform effectively",
    ],
  },
  {
    id: 1,
    title: "Pathways to Purpose: Exploring Your Career Story",
    description:
      "This session guides you through understanding your current career clarity, maturity in making career decisions, and crafting your unique life and career narrative.",
    duration: "30 min",
    icon: "Lightbulb",
    forms: [
      {
        id: "pre-assessment",
        title: "Pre Assessment",
        description:
          "Assess your current clarity, confidence, and readiness for your career journey.",
        estimatedTime: "5 min",
        status: "completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/session/1/q/pre-assessment",
        topics: ["Personal Info", "Current Goals", "Readiness for Change"],
        difficulty: "beginner",
      },
      {
        id: "career-maturity",
        title: "Career Maturity",
        description:
          "Reflect on your attitudes, beliefs, and confidence regarding career choices and planning.",
        estimatedTime: "8 min",
        status: "completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/1/q/career-maturity",
        topics: ["Career Beliefs", "Decision-Making", "Preparation"],
        difficulty: "beginner",
      },
      {
        id: "career-story-1",
        title: "Career Story 1",
        description:
          "Tell your unique story by describing your interests, inspirations, and envisioned career path.",
        estimatedTime: "17 min",
        status: "completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/session/1/q/career-story-1",
        topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
        difficulty: "beginner",
      },
    ],
    status: "completed",
    completedAt: "2025-07-22T09:08:00+05:30",
    score: 90,
    topics: ["Pre Assessment", "Career Maturity", "Career Story 1"],
    learningObjectives: [
      "Understand and assess your current career clarity and readiness for change",
      "Explore beliefs, attitudes, and influences on your career decision-making process",
      "Develop a personal narrative highlighting transitions, inspirations, and future aspirations",
    ],
  },

  // {
  //   id: 2,
  //   title: "Skills Assessment",
  //   description: "Identify your current skills and areas for development",
  //   duration: "25 min",
  //   icon: Target,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "completed",
  //   completedAt: "2024-01-14",
  //   score: 92,
  //   topics: ["Technical Skills", "Soft Skills", "Skill Gap Analysis"],
  // },
  // {
  //   id: 3,
  //   title: "Career Exploration",
  //   description: "Research different career paths and opportunities",
  //   duration: "40 min",
  //   icon: BookOpen,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "current",
  //   topics: ["Industry Research", "Job Market Analysis", "Career Paths"],
  // },
  // {
  //   id: 4,
  //   title: "Goal Setting",
  //   description: "Define your short-term and long-term career objectives",
  //   duration: "20 min",
  //   icon: Trophy,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["SMART Goals", "Career Milestones", "Action Planning"],
  // },
  // {
  //   id: 5,
  //   title: "Networking Strategies",
  //   description: "Learn how to build and leverage professional networks",
  //   duration: "35 min",
  //   icon: Users,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: [
  //     "LinkedIn Optimization",
  //     "Networking Events",
  //     "Relationship Building",
  //   ],
  // },
  // {
  //   id: 6,
  //   title: "Resume & Portfolio",
  //   description: "Create compelling resumes and showcase your work",
  //   duration: "45 min",
  //   icon: Briefcase,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["Resume Writing", "Portfolio Creation", "Personal Branding"],
  // },
  // {
  //   id: 7,
  //   title: "Interview Preparation",
  //   description: "Master the art of interviewing and negotiation",
  //   duration: "50 min",
  //   icon: Star,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: [
  //     "Interview Techniques",
  //     "Behavioral Questions",
  //     "Salary Negotiation",
  //   ],
  // },
  // {
  //   id: 8,
  //   title: "Job Search Strategy",
  //   description: "Develop effective job search and application strategies",
  //   duration: "30 min",
  //   icon: TrendingUp,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["Job Boards", "Application Strategy", "Follow-up Techniques"],
  // },
];

// {
//     id: 1,
//     title: "",
//     description: "",
//     duration: "",
//     icon: "Lightbulb",
//     forms: [
//       {
//         id: "pre-assessment",
//         title: "Pre Assessment",
//         description: "",
//         estimatedTime: "",
//         status: "",
//         completedAt: "",
//         score: ,
//         icon: "",
//         route: "",
//         topics: ,
//         difficulty: "",
//       },
//       {
//         id: "career-maturity",
//         title: "Career Maturity",
//         description: "",
//         estimatedTime: "",
//         status: "",
//         completedAt: "",
//         score: ,
//         icon: "",
//         route: "",
//         topics: ,
//         difficulty: "",
//       },
//       {
//         id: "career-story-1",
//         title: "Career Story 1",
//         description: "",
//         estimatedTime: "",
//         status: "",
//         completedAt: "",
//         score: ,
//         icon: "",
//         route: "",
//         topics: ,
//         difficulty: "",
//       },
//     ],
//     status: "",
//     completedAt: "",
//     score: ,
//     topics: [
//       "Pre Assessmentt",
//       "Career Maturity",
//       "Career Story 1",
//     ],
//   },
