export const isProductionEnvironment = process.env.NODE_ENV === "production";

export const isTestEnvironment = Boolean(
  process.env.PLAYWRIGHT_TEST_BASE_URL ||
    process.env.PLAYWRIGHT ||
    process.env.CI_PLAYWRIGHT
);

export const SESSION_TEMPLATES = [
  {
    id: 0,
    title: "Welcome & Orientation",
    description:
      "Get started with your career journey and understand the process",
    duration: "15 min", //duration for the full session
    icon: "Rocket",
    forms: [
      {
        id: "demographics-details",
        title: "Demographics Details",
        description: "Tell us about yourself and your career aspirations",
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2024-01-10",
        score: 100,
        icon: "User",
        route: "/journey/sessions/0/q/demographics-details",
        topics: ["Personal Info", "Professional Info", "Coaching Experience"],
        difficulty: "beginner",
      },
      {
        id: "schedule-call",
        title: "Schedule Call",
        description:
          "Book a personalized coaching session to discuss your progress and next steps",
        estimatedTime: "30 min",
        status: "not-completed",
        completedAt: null,
        score: null,
        icon: "Calendar",
        route: "/schedule",
        topics: ["One-on-One Coaching", "Progress Review", "Goal Setting"],
        difficulty: "beginner",
        prerequisites: ["demographics-details"],
      },
      {
        id: "session-feedback",
        title: "Session Feedback",
        description: "This is session feedback",
        prerequisites: ["demographics-details", "schedule-call"],
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/session-feedback?session=0",
        topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
        difficulty: "beginner",
      },
      {
        id: "session-report",
        title: "Session Report",
        description:
          "A comprehensive summary of your session, highlighting key insights, reflections, and progress made during the journey.",
        prerequisites: [
          "demographics-details",
          "schedule-call",
          "session-feedback",
        ],
        estimatedTime: "17 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/0/session-report",
        topics: ["Emotional Health", "Personal Progress", "Future Goals"],
      },
    ],
    status: "locked",
    completedAt: "2024-01-10",
    score: 95,
    topics: ["Demographics Details"],
    learningObjectives: [
      "Understand the career exploration process",
      "Set initial career goals",
      "Navigate the platform effectively",
    ],
  },
  {
    id: 1,
    title: "Pathways to Purpose",
    description:
      "This session guides you through understanding your current career clarity, maturity in making career decisions, and crafting your unique life and career narrative.",
    duration: "30 min",
    icon: "Lightbulb",
    forms: [
      {
        id: "pre-assessment",
        title: "Pre Assessment",
        description:
          "Assess your current clarity, confidence, and readiness for your career journey.",
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/1/q/pre-assessment",
        topics: ["Personal Info", "Current Goals", "Readiness for Change"],
        difficulty: "beginner",
      },
      {
        id: "career-maturity",
        title: "Career Maturity",
        description:
          "Reflect on your attitudes, beliefs, and confidence regarding career choices and planning.",
        estimatedTime: "8 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/1/q/career-maturity",
        topics: ["Career Beliefs", "Decision-Making", "Preparation"],
        difficulty: "beginner",
        prerequisites: ["pre-assessment"],
      },
      // {
      //   id: "career-story-1",
      //   title: "Career Story 1",
      //   description:
      //     "Tell your unique story by describing your interests, inspirations, and envisioned career path.",
      //   estimatedTime: "17 min",
      //   status: "not-completed",
      //   completedAt: "2025-07-22T09:08:00+05:30",
      //   score: 100,
      //   icon: "User",
      //   route: "/journey/sessions/1/a/career-story-1",
      //   topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
      //   difficulty: "beginner",
      // },
      {
        id: "schedule-call",
        title: "Schedule Call",
        description:
          "Book a personalized coaching session to discuss your progress and next steps",
        estimatedTime: "30 min",
        status: "not-completed",
        completedAt: null,
        score: null,
        icon: "Calendar",
        route: "/schedule",
        topics: ["One-on-One Coaching", "Progress Review", "Goal Setting"],
        difficulty: "beginner",
        prerequisites: ["pre-assessment", "career-maturity"],
      },
      {
        id: "session-feedback",
        title: "Session Feedback",
        description: "This is session feedback",
        prerequisites: ["pre-assessment", "career-maturity", "schedule-call"],
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/session-feedback?session=1",
        topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
        difficulty: "beginner",
      },
      {
        id: "session-report",
        title: "Session Report",
        description:
          "A comprehensive summary of your session, highlighting key insights, reflections, and progress made during the journey.",
        prerequisites: [
          "pre-assessment",
          "career-maturity",
          "schedule-call",
          "session-feedback",
        ],
        estimatedTime: "17 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/1/session-report",
        topics: ["Emotional Health", "Personal Progress", "Future Goals"],
      },
    ],
    status: "locked",
    completedAt: "2025-07-22T09:08:00+05:30",
    score: 90,
    topics: ["Pre Assessment", "Career Maturity", "Career Story 1"],
    learningObjectives: [
      "Understand and assess your current career clarity and readiness for change",
      "Explore beliefs, attitudes, and influences on your career decision-making process",
      "Develop a personal narrative highlighting transitions, inspirations, and future aspirations",
    ],
  },

  {
    id: 2,
    title: "Discovering Your Unique Talents",
    description:
      "This session helps you explore your personal strengths, interests, and values through validated assessments and creative reflection. By the end, you’ll gain insights into your personality, career interests, and the bigger picture of what makes you thrive.",
    duration: "40 min",
    icon: "Star",
    forms: [
      {
        id: "riasec-test",
        title: "RIASEC Interest Profiler",
        description:
          "Identify your dominant career interest themes using the RIASEC model and discover which career fields best match your preferences.",
        estimatedTime: "10 min",
        // status: "not started",
        status: "not-completed",
        completedAt: null,
        score: null,
        icon: "Compass",
        route: "/journey/sessions/2/q/riasec-test",
        topics: ["Career Interests", "RIASEC Model", "Career Fit"],
        difficulty: "beginner",
      },
      {
        id: "personality-test",
        title: "Personality Profile",
        description:
          "Learn about your core traits, work styles, and how your personality influences your career preferences and relationships.",
        estimatedTime: "12 min",
        // status: "not started",
        status: "not-completed",
        completedAt: null,
        score: null,
        icon: "Smile",
        route: "/journey/sessions/2/q/personality-test",
        topics: ["Personality Traits", "Self-Discovery", "Work Style"],
        difficulty: "beginner",
        prerequisites: ["riasec-test"],
      },
      // {
      //   id: "life-collage",
      //   title: "My Life Collage",
      //   description:
      //     "Create a visual and reflective collage to express what energizes you, your values, and your dreams—bringing your unique story to life.",
      //   estimatedTime: "18 min",
      //   status: "completed",
      //   completedAt: null,
      //   score: null,
      //   icon: "Image",
      //   route: "/journey/sessions/2/q/life-collage",
      //   topics: ["Self-Expression", "Life Values", "Vision"],
      //   difficulty: "beginner",
      // },
      {
        id: "schedule-call",
        title: "Schedule Call",
        description:
          "Book a personalized coaching session to discuss your progress and next steps",
        estimatedTime: "30 min",
        status: "not-completed",
        completedAt: null,
        score: null,
        icon: "Calendar",
        route: "/schedule",
        topics: ["One-on-One Coaching", "Progress Review", "Goal Setting"],
        difficulty: "beginner",
        prerequisites: ["riasec-test", "personality-test"],
      },
      {
        id: "session-feedback",
        title: "Session Feedback",
        description: "This is session feedback",
        prerequisites: ["riasec-test", "personality-test", "schedule-call"],
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/session-feedback?session=2",
        topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
        difficulty: "beginner",
      },
      {
        id: "session-report",
        title: "Session Report",
        description:
          "A comprehensive summary of your session, highlighting key insights, reflections, and progress made during the journey.",
        prerequisites: [
          "riasec-test",
          "personality-test",
          ,
          "schedule-call",
          "session-report",
        ],
        estimatedTime: "17 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/2/session-report",
        topics: ["Emotional Health", "Personal Progress", "Future Goals"],
      },
    ],
    status: "locked",
    completedAt: null,
    score: null,
    topics: ["RIASEC Profile", "Personality Profile", "Life Collage"],
    learningObjectives: [
      "Identify your core interests and understand how they align with potential career fields",
      "Recognize your unique personality traits and how they impact your work and interactions",
      "Express your life story, aspirations, and values through creative means",
    ],
  },

  {
    id: 3,
    title: "Building Psychological Strength and Reflection",
    description:
      "This session focuses on assessing your psychological wellbeing and deepening your career narrative. Through validated assessments and storytelling, you'll understand your mental health, resilience, and how your past experiences shape your future ambitions.",
    duration: "35 min",
    icon: "HeartPulse",
    forms: [
      {
        id: "psychological-wellbeing",
        title: "Psychological Wellbeing Assessment",
        description:
          "Evaluate aspects of your emotional health, resilience, and positive functioning. This assessment helps you recognize strengths and areas for growth in your mental wellbeing.",
        estimatedTime: "15 min",
        status: "not started",
        completedAt: null,
        score: null,
        icon: "Activity",
        route: "/journey/sessions/3/q/psychological-wellbeing",
        topics: ["Wellbeing", "Mental Health", "Resilience"],
        difficulty: "intermediate",
      },
      {
        id: "career-story-2",
        title: "Career Story – 2",
        description:
          "Continue your career story, reflecting on key transitions, challenges, and moments of inspiration. Articulate your evolving aspirations and how your wellbeing supports your journey.",
        estimatedTime: "20 min",
        status: "not started",
        completedAt: null,
        score: null,
        icon: "Book",
        route: "/journey/sessions/3/q/career-story-2",
        topics: ["Narrative", "Career Reflection", "Personal Growth"],
        difficulty: "intermediate",
      },
      {
        id: "session-feedback",
        title: "Session Feedback",
        description: "This is session feedback",
        prerequisites: ["psychological-wellbeing"],
        estimatedTime: "5 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/session-feedback?session=3",
        topics: ["Career Narrative", "Inspirations", "Personal Reflection"],
        difficulty: "beginner",
      },
      {
        id: "session-report",
        title: "Session Report",
        description:
          "A comprehensive summary of your session, highlighting key insights, reflections, and progress made during the journey.",
        prerequisites: ["psychological-wellbeing"],
        estimatedTime: "17 min",
        status: "not-completed",
        completedAt: "2025-07-22T09:08:00+05:30",
        score: 100,
        icon: "User",
        route: "/journey/sessions/3/session-report",
        topics: ["Emotional Health", "Personal Progress", "Future Goals"],
        difficulty: "beginner",
      },
    ],
    status: "locked",
    completedAt: null,
    score: null,
    topics: ["Wellbeing", "Career Narrative"],
    learningObjectives: [
      "Assess and understand your psychological wellbeing and resilience",
      "Reflect on important events shaping your career and identity",
      "Integrate self-awareness and personal growth into your career journey",
    ],
  },

  // {
  //   id: 4,
  //   title: "Goal Setting",
  //   description: "Define your short-term and long-term career objectives",
  //   duration: "20 min",
  //   icon: Trophy,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["SMART Goals", "Career Milestones", "Action Planning"],
  // },
  // {
  //   id: 5,
  //   title: "Networking Strategies",
  //   description: "Learn how to build and leverage professional networks",
  //   duration: "35 min",
  //   icon: Users,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: [
  //     "LinkedIn Optimization",
  //     "Networking Events",
  //     "Relationship Building",
  //   ],
  // },
  // {
  //   id: 6,
  //   title: "Resume & Portfolio",
  //   description: "Create compelling resumes and showcase your work",
  //   duration: "45 min",
  //   icon: Briefcase,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["Resume Writing", "Portfolio Creation", "Personal Branding"],
  // },
  // {
  //   id: 7,
  //   title: "Interview Preparation",
  //   description: "Master the art of interviewing and negotiation",
  //   duration: "50 min",
  //   icon: Star,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: [
  //     "Interview Techniques",
  //     "Behavioral Questions",
  //     "Salary Negotiation",
  //   ],
  // },
  // {
  //   id: 8,
  //   title: "Job Search Strategy",
  //   description: "Develop effective job search and application strategies",
  //   duration: "30 min",
  //   icon: TrendingUp,
  //   forms: [
  //     {
  //       id: "pre-assessment",
  //       title: "Pre Assessment",
  //       estimatedTime: "5 min",
  //       difficulty: "beginner",
  //     },
  //     {
  //       id: "career-story-1",
  //       title: "Career Story 1",
  //       estimatedTime: "10 min",
  //       difficulty: "beginner",
  //     },
  //   ],
  //   status: "locked",
  //   topics: ["Job Boards", "Application Strategy", "Follow-up Techniques"],
  // },
];
